apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
spec:
  containers:
  - name: nginx
    image: tcr.aocs-int.t-systems-service.com/training/nginx-unprivileged:1.22
    ports:
    - containerPort: 8080