apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss-army-knife-deployment
spec:
  selector:
    matchLabels:
      app: swiss-army-knife
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: swiss-army-knife
    spec:
      containers:
      - name: swiss-army-knife
        image: tcr.aocs-int.t-systems-service.com/training/swiss-army-knife:v0.12
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001