apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: tcr.aocs-int.t-systems-service.com/training/nginx-unprivileged:1.22
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: temp-path
      restartPolicy: Always
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 101
      volumes:
      - emptyDir: {}
        name: temp-path